name: ruff CI 

on: 
    push:
        # branches:
        #     - dev

jobs: 
    ruff: 
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3         

            - name: setup python
              uses: actions/setup-python@v5
              with: 
                python-version: "3.12"
            - name: install ruff
              run: pip install ruff
              
            - name: lint
              run: ruff check .

            - name: format check
              run: ruff format --check

            - name: formating
              run: ruff format
            